version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PROD=${PROD}
        - TARGET=${TARGET}
    ports:
      - 4300:4300
    depends_on:
      - db
    volumes:
      - .:/app
      - ./../../dbs/images_data:/app/upload
    restart: always

  db:
    image: postgres:15
    env_file: ./prod.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - ./../../dbs/hw_db/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8887:8080

volumes:
  pg_data:
  images_data:
