version: '3.8'
services:
  api:
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
      - .:/app
      - images_data:/app/upload
    restart: always

  db:
    image: postgres
    restart: always
    volumes:
      - ../../dbs/hot_wheels_db:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8887:8080

volumes:
  pg_data:
  images_data:
