version: '3.8'
services:
  api:
    build: .
    env_file:
      - ./dev.env
    ports:
      - 4300:4300
    depends_on:
      - db
    volumes:
      - .:/app
      - images_data:/app/upload
    restart: always

  db:
    image: postgres
    env_file:
      - ./dev.env
    restart: always
    volumes:
      - ./../../dbs/hw_db/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8887:8080

volumes:
  pg_data:
  images_data:
